name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      mingwTargetZip: cpp-httplib-playground-${{ github.ref_name }}-mingw64-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - uses: actions/checkout@v3
      
      - name: curl x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        shell: cmd
        run: |
          curl https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z -L -O -J &&^
          7z.exe x x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
          
      - name: curl openssl-v3.0.5-x86_64-posix-seh-rev0-8.1.0.zip
        shell: cmd
        run: |
          curl https://github.com/dirkarnez/openssl-prebuilt/releases/download/v3.0.5/openssl-v3.0.5-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -L -O &&^
          7z.exe x openssl-v3.0.5-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -o"openssl-v3.0.5-mingw64-x86_64-posix-seh-rev0-8.1.0" &&^
          cd openssl-v3.0.5-mingw64-x86_64-posix-seh-rev0-8.1.0 &&^
          dir

      - name: curl cpp-httplib-v0.14.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip
        shell: cmd
        run: |
          curl https://github.com/dirkarnez/cpp-httplib-prebuilt/releases/download/v0.14.0/cpp-httplib-v0.14.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -L -O &&^
          7z.exe x cpp-httplib-v0.14.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -o"cpp-httplib-v0.14.0-mingw64-x86_64-posix-seh-rev0-8.1.0" &&^
          cd cpp-httplib-v0.14.0-mingw64-x86_64-posix-seh-rev0-8.1.0 &&^
          dir
          
      - name: curl PortableGit-2.38.1-64-bit.7z.exe
        shell: cmd
        run: curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe && dir && 7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"PortableGit-2.38.1-64-bit"
      
      - name: curl cmake-3.24.0-windows-x86_64.zip
        shell: cmd
        run: curl https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip -L --output cmake-3.24.0-windows-x86_64.zip && dir && 7z.exe x cmake-3.24.0-windows-x86_64.zip

      - shell: cmd
        run: |
          cd /d "cmake-3.24.0-windows-x86_64\share\cmake-3.24\Modules\" &&^
          del /f FindOpenSSL.cmake &&^
          dir
        
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
            set PATH=^
            ${{ github.workspace }}\mingw64;^
            ${{ github.workspace }}\mingw64\bin;^
            ${{ github.workspace }}\cmake-3.24.0-windows-x86_64\bin;
            set CD_LINUX=%CD:\=/%
            gcc --version &&^
            cmake.exe -G"MinGW Makefiles" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -Dhttplib_DIR="%CD_LINUX%/cpp-httplib-v0.14.0-mingw64-x86_64-posix-seh-rev0-8.1.0/lib/cmake/httplib" ^
            -DOpenSSL_DIR="%CD_LINUX%/openssl-v3.0.5-mingw64-x86_64-posix-seh-rev0-8.1.0" ^
            -DCMAKE_INSTALL_PREFIX="cmake-build/${{ env.cmakeInstallationPath }}" -B./cmake-build &&^
            cd cmake-build && cmake --build . && cmake --install . 
            
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "cmake-build"
          filename: "${{ env.mingwTargetZip }}"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cmake-build/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
